import React from "react";

export default function Section2() {
    const data=[
        "You mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the individual using the Service.",
        'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Diveroid. For the purpose of the GDPR, the Company is the Data Controller.',
        "Application means the software program provided by the Company downloaded by You on any electronic device, named Diveroid 3.0.",
        'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
        'Account means a unique account created for You to access our Service or parts of our Service.',
        'Service refers to the Application.',
        'Country refers to: South Korea',
        'Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors.',
        'Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service(e.g. Google, Facebook).',
        'Personal Data is any information that relates to an identified or identifiable individual. For the purposes for GDPR, Personal Data means any information relating to You such as a name,e-mail, an identification number, location data, device data,online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity. For the purposes of the CCPA, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.',
        'Device means any device that can access the Service such as a computer, a cellphone or a digital tablet and devices purchased from our portal which can be connected with your device using BLE, wifi.',
        'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, Registered Device with your account can connect only).',
        'Data Controller, for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.',
        'Do Not Track (DNT) is a concept that has been promoted by US regulatory authorities, in particular the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and implement a mechanism for allowing internet users to control the tracking of their online activities across websites.',
        "Business, for the purpose of the CCPA (California Consumer Privacy Act), refers to the Company as the legal entity that collects Consumers' personal information and determines the purposes and means of the processing of Consumers' personal information, or on behalf of which such information is collected and that alone, or jointly with others, determines the purposes and means of the processing of consumers' personal information, that does business in the State of California.",
        'Consumer, for the purpose of the CCPA (California Consumer Privacy Act), means a natural person who is a California resident. A resident, as defined in the law, includes (1) every individual who is in the USA for other than a temporary or transitory purpose, and (2) every individual who is domiciled in the USA who is outside the USA for a temporary or transitory purpose.',
        "Sale, for the purpose of the CCPA (California Consumer Privacy Act), means selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating orally, in writing, or by electronic or other means, a Consumer's Personal information to another business or a third party for monetary or other valuable consideration."

     
    ]
  return (
    <section className="flex flex-col gap-4">
      <h1 className="underline text-[25px] font-bold">
        Interpretation and Definitions :
      </h1>

      <div className="flex flex-col gap-2">
        <h1 className="font-extrabold text-[18px]">Interpretation</h1>


        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions.</p>
        <p>The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
      </div>
      <div className="flex flex-col gap-2">
        <h1 className="font-extrabold text-[18px]">Definitions</h1>
        <h2>For the purposes of this Privacy Policy:</h2>
        {data.map((item, index)=>(
              <ul key={index} className="flex flex-col list-disc list-inside pl-4">
              <li>{item}</li>
          </ul>


        ))}
      


      </div>
    </section>
  );
}
